"""Add created_on to authors and papers

Revision ID: d67252bc1cd1
Revises: cde4eec6f497
Create Date: 2025-01-27 13:58:41.027792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd67252bc1cd1'
down_revision: Union[str, None] = 'cde4eec6f497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_authors_id'), 'authors', ['id'], unique=False)
    op.create_table('papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('pdf', sa.String(), nullable=True),
    sa.Column('journal', sa.String(), nullable=True),
    sa.Column('publication_year', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_papers_id'), 'papers', ['id'], unique=False)
    op.create_table('business_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_paper', sa.Integer(), nullable=False),
    sa.Column('business_score', sa.Float(), nullable=True),
    sa.Column('business_score_adjusted', sa.Float(), nullable=True),
    sa.Column('business_score_justification', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_paper'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_scores_id'), 'business_scores', ['id'], unique=False)
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_paper', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_paper'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keywords_id'), 'keywords', ['id'], unique=False)
    op.create_table('paper_authors',
    sa.Column('id_paper', sa.Integer(), nullable=False),
    sa.Column('id_author', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_author'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['id_paper'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id_paper', 'id_author')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paper_authors')
    op.drop_index(op.f('ix_keywords_id'), table_name='keywords')
    op.drop_table('keywords')
    op.drop_index(op.f('ix_business_scores_id'), table_name='business_scores')
    op.drop_table('business_scores')
    op.drop_index(op.f('ix_papers_id'), table_name='papers')
    op.drop_table('papers')
    op.drop_index(op.f('ix_authors_id'), table_name='authors')
    op.drop_table('authors')
    # ### end Alembic commands ###
